spring:
  datasource:
    url: jdbc:h2:mem://localhost/~/jpashop;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          #          show_sql: true
          format_sql: true
          default_batch_fetch_size: 100

  h2:
    console:
      path: /h2-console
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
